### PR TITLE
Adds eslint and fixes (most of) the linter errors

### PR DESCRIPTION
**Pull request by TomAFrench**
Also I hate you for renaming all the files in between me forking and merging.

### CODE REVIEW

**Comment by TomAFrench** [comment]
I also hate you for indenting with 4 spaces.

**Comment by h0go** [comment]
erm m8

\> be me
\> sat at my computer
\> see some stupid pull request
\> m8888 obviously using tabs to indent is better than using spaces z0mg
\> this is my website m9 back off
\> ??????
\> profit

**Comment by TomAFrench** [comment]
you should feel right at home then

**Comment by SarahFrench** [comment]
- [x] cause a lame ~~flame~~ war in the PR

**Pull request merged**
